### ISSUE TITLE
Error in filtering data with missing values

### ISSUE THREAD

**Issue by webermarcolivier** [zimmerlab/MS-EmpiRe#8]
When filtering data with missing values, the function `filter_detection_rate` fails.

https://github.com/zimmerlab/MS-EmpiRe/blob/6d7056dccea06f50e82022fad32125fe59596e39/R/filter.R#L33

should be
```R
s <- (x > 0 & !is.na(x)) %*% condition
```

**Comment by zimmerlab** [comment]
Hi @webermarcolivier , thank you for the hint, the issue just got fixed.
