### ISSUE TITLE
output is not 100% deterministic?

### ISSUE THREAD

**Issue by vnaum** [zimmerlab/MS-EmpiRe#9]
I tried feeding same data to MS-Empire, and noticed results on each run
are different. Close, but not exactly the same.

I'm not sure if this really is an issue or not, but isn't output
determined solely by input (completely deterministic)? Or theres some
randomity in the algorithm?

same data row over 4 runs:
```
score,p.val,log2FC,prot.p.val,prot.sd,prot.s,p.adj,prot.p.adj,prot.id
1.2210217648120691,0.22207777922220773,-0.3405161248683167,0.19347888951402803,14.966629547095765,19.46195061409111,0.9074396862143431,0.8530918877361343,A0A075M3N4
1.2209161241464461,0.22211777882221173,-0.3405161248683167,0.19347888951402803,14.966629547095765,19.46195061409111,0.9130770338531293,0.8530918877361343,A0A075M3N4
1.2181215961239962,0.22317776822231772,-0.3405161248683167,0.19347888951402803,14.966629547095765,19.46195061409111,0.9098143440454385,0.8530918877361343,A0A075M3N4
1.2192277231223836,0.2227577724222758, -0.3405161248683167,0.19347888951402803,14.966629547095765,19.46195061409111,0.9104192806869181,0.8530918877361343,A0A075M3N4
```

**Comment by grubermar** [comment]
Hi @vnaum ,

yes, there are a few steps that produce slightly different output each time, e.g. the generation of decoy distributions for the outlier score correction (uses rnorm). You can get around that behavior by calling the "set.seed" function of R at the beginning of your analysis.
Next version of MS-EmpiRe will be shipped with either pre-computed background distributions and/or the possibility to set a seed in the relevant functions for clarification.

Best regards,
Markus
